package com.wuxian.janus.core.synchronism;

public enum TenantChangePart {
    SCOPE_USER_GROUP_USER,
    USER_GROUP,
    USER_GROUP_USER,

    SCOPE_SINGLE_ROLE_USER,
    SINGLE_PERMISSION,
    SINGLE_ROLE_PERMISSION,
    SINGLE_ROLE,
    SINGLE_ROLE_OTHER,
    SINGLE_ROLE_USER_GROUP,
    SINGLE_ROLE_USER,

    SCOPE_MULTIPLE_ROLE_USER,
    MULTIPLE_PERMISSION,
    MULTIPLE_ROLE_PERMISSION,
    MULTIPLE_ROLE,
    MULTIPLE_ROLE_OTHER,
    MULTIPLE_ROLE_USER_GROUP,
    MULTIPLE_ROLE_USER,
}